GET http://localhost:8080/dashboard/overview
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicGV0ZXJzb24iLCJpYXQiOjE2MDI5NDcxNzMsImV4cCI6MTYwMjk5MDM3M30.QId_vzFRwZKsP8Dl0eUQsdPyyjhgBDGQouD3WeGkbze1taI5UPBwpK42LQ9DmjhxDlTGwrU0cMph06lmLbGBDw