name: Angular CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: |
        cd frontend && npm ci --legacy-peer-deps
        cd ../backend && npm ci --legacy-peer-deps
      
    - name: Build Project
      env:
        NG_CLI_ANALYTICS: false
        NODE_OPTIONS: --openssl-legacy-provider
      run: |
        cd frontend && npm run build --if-present
        cd ../backend && npm run build --if-present
